from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq
import uuid
import json
import os
from datetime import datetime

load_dotenv()

app = Flask(__name__)
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# In-memory audit log
audit_log = []


def llm_signal(text: str) -> float:
    """Signal 1: Ask Groq whether text is AI-generated. Returns 0.0-1.0."""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": """You are an AI content detector. Analyze the text and return ONLY a JSON object.
Assess whether the text was written by a human or generated by AI.

Respond with ONLY this JSON format, nothing else:
{"score": 0.85, "reasoning": "one sentence explanation"}

Where score is 0.0 (clearly human) to 1.0 (clearly AI-generated)."""
            },
            {"role": "user", "content": text}
        ],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    try:
        result = json.loads(raw)
        return float(result.get("score", 0.5))
    except Exception:
        return 0.5


def stylometric_signal(text: str) -> float:
    """Signal 2: Measure statistical uniformity of text. Returns 0.0-1.0."""
    import re
    sentences = re.split(r'[.!?]+', text.strip())
    sentences = [s.strip() for s in sentences if len(s.strip()) > 0]

    if len(sentences) < 2:
        return 0.5

    # Sentence length variance (low variance = more AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    variance_score = 1.0 - min(variance / 100, 1.0)  # high variance = human

    # Type-token ratio (low diversity = more AI-like)
    words = text.lower().split()
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)
    ttr_score = 1.0 - ttr  # low TTR = AI-like

    return round((variance_score + ttr_score) / 2, 3)


def get_label(score: float) -> str:
    """Map confidence score to transparency label text."""
    if score > 0.75:
        return (
            "This content was likely AI-generated. Our system detected patterns "
            "consistent with AI writing tools. If this is your original work, "
            "you can submit an appeal."
        )
    elif score >= 0.45:
        return (
            f"We were unable to determine with confidence whether this content "
            f"is AI-generated or human-written. Confidence score: {score:.2f}. "
            f"You may appeal if you believe this is incorrect."
        )
    else:
        return "This content appears to be human-written. No action required."


def get_attribution(score: float) -> str:
    if score > 0.75:
        return "likely_ai"
    elif score >= 0.45:
        return "uncertain"
    else:
        return "likely_human"


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data:
        return jsonify({"error": "Missing 'text' field"}), 400

    text = data["text"]
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = round((llm_score * 0.6) + (stylo_score * 0.4), 3)

    attribution = get_attribution(confidence)
    label = get_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    audit_log.append(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id")
    reasoning = data.get("creator_reasoning", "")

    entry = next((e for e in audit_log if e["content_id"] == content_id), None)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    entry["status"] = "under_review"
    entry["appeal_reasoning"] = reasoning

    return jsonify({
        "message": "Appeal received. Your content is now under review.",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": audit_log})


if __name__ == "__main__":
    app.run(debug=True)